### ISSUE TITLE
Доставать количество скачиваний

### ISSUE THREAD

**Issue by lapanoid** [spb-frontend/spb-frontend.ru#20]
https://developers.google.com/url-shortener/v1/getting_started

**Comment by sharikovvladislav** [comment]
Количество скачиваний = количество переходов по ссылке, всё верно?

Кстати, не знаешь у гугла частичный запрос атрибутов есть? Чтобы получить только 1 поле, а не громоздкий json. Кстати, там еще тонна параметров, можно попробовать придумать какую-то расширенную статистику или что-то более веселое.

Как конкретно планируете выводить полученное кол-во скачиваний?

**Comment by lapanoid** [comment]
Да можно колво переходов.. Выводить как soudcloud например http://prntscr.com/gaf2ea

**Comment by lapanoid** [comment]
Расширенную - это потом, щас хотя бы как-то, а то людям, которые заходят на сайт вообще не понятно слушает кто-то или нет

**Comment by sharikovvladislav** [comment]
Кстати, про: 

> не понятно слушает кто-то или нет 

Дак может нам впервую очередь нужна статистика нажатий на кнопку Play тогда?

Кстати, а с iTunes можно вытащить кол-во скачиваний / прослушиваний?

**Comment by lapanoid** [comment]
@Akurganow смотрел, не нашел как с iTunes достать

**Comment by sharikovvladislav** [comment]
Если кто возьмется делать. Нужно будет делать примерно такой запрос: 

curl 'https://www.googleapis.com/urlshortener/v1/url?shortUrl=<short url>&projection=ANALYTICS_CLICKS&key=<api_key>'

short url, например https://goo.gl/btkTtU (1-ый подкаст)
api_key получать у гугла: https://developers.google.com/url-shortener/v1/getting_started#APIKey

Вопросы: 
- какой API key предлагается использовать в продакшене? кто его должен генерить? я могу сам например сгенерить. но если я зло какое-то и удалю потом его (но я не такой 😼 )? будет нехорошо. как здесь поступить?
- где на данный момент предлагается выводить кол-во скачиваний? прямо в плеере не получится. если я всё правильно понял, то тут используется audio, а у него ничего дополнительного добавить как я понял нельзя: https://www.w3schools.com/tags/att_audio_controls.asp. разве что отключать всё и делать как-то кастомно - своё.
- чем принято в react делать запросы? axios? или fetch достаточно? или чем?
