### ISSUE TITLE
Добавить ссылку на айтюнс

### ISSUE THREAD

**Issue by lapanoid** [spb-frontend/spb-frontend.ru#24]

**Comment by sharikovvladislav** [comment]
Куда вы хотите добавить ссылку? Здесь? http://spb-frontend.ru/podcast/

Что-то вроде "наш подкаст доступен в iTunes" вот ссылка?

**Comment by lapanoid** [comment]
Ага, но лучше оформить в виде кнопки itunes

**Comment by sharikovvladislav** [comment]
ЧТо-то вроде https://www.apple.com/itunes/link/ ?

**Comment by lapanoid** [comment]
ага
