### ISSUE TITLE
Форматировать дату на странице подкаста и в списке подкастов (человеко читаемая дата вместо YYYY-MM-DD)

### ISSUE THREAD

**Issue by sharikovvladislav** [spb-frontend/spb-frontend.ru#33]
Например, в 28 июля 2017 в данном случае: http://spb-frontend.ru/podcast/1/ (или 1 подкаст в списке http://spb-frontend.ru/podcast/)

**Comment by sharikovvladislav** [comment]
Можно/нужно ли использовать что-то вроде momentjs или plain old Date object?

**Comment by lapanoid** [comment]
@sharikovvladislav я не против moment, если только отрубить лишние локали https://stackoverflow.com/a/25426019/1427399.

**Comment by sharikovvladislav** [comment]
@lapanoid да про локали известная тема. ок.

**Comment by sharikovvladislav** [comment]
Общая идея такая: 
- [ ] добавляем модуль в котором будет лежать ф-ия для форматирования даты
- [ ] используем moment, не забываем про ContextReplacementPlugin/IgnorePlugin
- [ ] в два компонента добавляем модуль для форматирования даты и используем.

Всё так? Или я где-то не прав?

**Comment by sharikovvladislav** [comment]
Fixed
