### ISSUE TITLE
Feature request: в плеере выставлять время на основании данных в url

### ISSUE THREAD

**Issue by sharikovvladislav** [spb-frontend/spb-frontend.ru#34]
Пример: https://youtu.be/72NfSwCzFVE?t=338

Зачем: сейчас хотел товарищу кинуть ссылку на подкаст сразу же на нужное место. Не смог этого сделать :)

**Comment by lapanoid** [comment]
Смерджил https://github.com/spb-frontend/spb-frontend.ru/pull/41
