### ISSUE TITLE
В мобильном хроме не отображаются подкасты

### ISSUE THREAD

**Issue by vkabish** [spb-frontend/spb-frontend.ru#46]
В мобильном хроме по ссылке /podcast не отображается блок `main.page--content` из-за этого не могу послушать ваш замечательный подкаст. Может я один такой. 0_о
Приложил линки на скрины..
[раз](https://goo.gl/Mfe5fU)
[два](https://goo.gl/YCE2G2)

**Comment by NumminorihSF** [comment]
такаяже проблема была, но телефон решил сбросить все настройки, и все заработало (отчистка кэша не помогала), поэтому отладить пока негде.
причина там в сервис воркере, который то-ли не обновляет файлы, то-ли в у него запрашиваются не те файлы, но он на все запросы возвращает 404

**Comment by lapanoid** [comment]
@NumminorihSF @vkabish проверьте плиз, осталась ли проблема, вот это должно фиксить https://github.com/spb-frontend/spb-frontend.ru/pull/48

**Comment by NekR** [comment]
@lapanoid Я даже заморочился и написал тесты тогда: https://github.com/NekR/self-destroying-sw/blob/master/tests/service-worker/test.js
Должно всё починиться :-)

**Comment by NumminorihSF** [comment]
@lapanoid у меня все работает, но как писал выше, оно и работало до этого (после того, как все настройки слетели)
