### ISSUE TITLE
Кнопка "загрузки" подкаста (Firefox 57.0.1)

### ISSUE THREAD

**Issue by jo-a9018yo** [spb-frontend/spb-frontend.ru#53]
Кнопка "загрузки" подкаста отсутствует в Firefox 57.0.1

**Comment by Akurganow** [comment]
Кнопки "загрузки" теперь вообще нет, в новом плеере она не предусмотрена

**Comment by lapanoid** [comment]
@akurganow так может надо.. Предусмотреть?)

**Comment by Akurganow** [comment]
#67
