### ISSUE TITLE
Страница спикеров на митапе/гостей подкаста

### ISSUE THREAD

**Issue by lapanoid** [spb-frontend/spb-frontend.ru#58]
1) Забрать данные из контентфул

посмотреть данные можно запустив `npm run develop` и открыв
http://localhost:8000/___graphql?query=%7B%0A%20%20%20%20%20%20allContentfulPerson%20%7B%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20lastname%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20position%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20vk%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20telegram%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20twitter%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20slack%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20photo%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20company%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20talks%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20podcasts%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D

```
{
      allContentfulPerson {
        edges {
          node {
            name,
            lastname,
            position,
            vk,
            telegram,
            twitter,
            slack,
            photo {
              id
            },
            company,
            talks {
              id
            },
            podcasts {
              id
            }
          }
        }
      }
    }
```

2) Сделать страницы спикеров/гостей

**Comment by lapanoid** [comment]
![image](https://user-images.githubusercontent.com/154949/37570396-640d6852-2b00-11e8-9df0-11f896cc8e61.png)

**Comment by dshved** [comment]
@lapanoid почему-то нет поля `talks`

**Comment by lapanoid** [comment]
у нас нет докладов на сайте пока @dshved

**Comment by lapanoid** [comment]
Проще сделать для подкаста вначале, потом перенесем доклады

**Comment by dshved** [comment]
А ссылки какие должны быть со списком всех участников подкаста и конкретного участника?

**Comment by lapanoid** [comment]
@dshved страница одного человека просто, остальное потом. Можно будет ссылки давать тогда на людей

**Comment by lapanoid** [comment]
@dshved сделал в https://github.com/spb-frontend/spb-frontend.ru/pull/60
