### ISSUE TITLE
Доработки плеера

### ISSUE THREAD

**Issue by MikeDevice** [spb-frontend/spb-frontend.ru#62]
Впервые зашёл на этот сайт послушать [подкаст](https://spb-frontend.ru/podcast/26/). Меня порадовал внешний вид плеера, и казалось, что этим можно пользоваться, но, чем дальше я слушал, тем больше сталкивался с некоторыми неудобствами.

## Фокус на прогресс баре
Его нет, следовательно нельзя с клавиатуры с ним взаимодействовать. Мне несколько раз нужно было перемотать назад где-то на 5--10 секунд, и каждый раз мне приходилось делать это мышкой.

_Возможное решение_
Вообще хотелось бы иметь фокус не на прогресс баре, а на всём плеере сразу. Допустим, сейчас плеер в фокусе, и пользователь может с клавиатуры перематывать (`←` и `→`), добавлять громкость (`↓` и `↑`), воспроизводить и останавливать (`space`), и что-нибудь ещё (менять ту же скорость, например).

Мне кажется, это было бы удобно.

## Сколько осталось до конца записи
В какой-то момент времени, стало интересно, сколько вообще длится подкаст, и я интуитивно кликнул мышкой по тексту, показывающий, сколько времени уже прошло. Я ожидал, что там появится оставшееся время (вместо прошедшего), но такого не произошло.

**Comment by lex111** [comment]
И еще большая просьба, можно сделать сохранение текущего времени воспроизведения не в урле, а в локальном хранилище, не очень классно сейчас подобная картина:

![image](https://user-images.githubusercontent.com/4408379/37800880-6c60077a-2e35-11e8-8f4c-0701e24d441c.png)

**Comment by MikeDevice** [comment]
Да можно так же оставить в урле (если это действительно удобно и нужно), но, при смене урла, не пушить в историю браузера, а делать замену — `history.replaceState()`

**Comment by Akurganow** [comment]
@MikeDevice У нас и так replaceState https://github.com/spb-frontend/spb-frontend.ru/blob/master/src/components/Player/index.js#L24

**Comment by MikeDevice** [comment]
@Akurganow да, действительно. Я почему-то думал, что `replaceState` заменяет запись в истории напрямую в браузере, однако, погуглив, понял, что это не так.

**Comment by Akurganow** [comment]
Можно убрать запись в урл, но оставить чтение и тогда надо будет сделать блок share как у youtube
