### ISSUE TITLE
Добавить кнопку загрузки на страницу выпуска

### ISSUE THREAD

**Issue by Akurganow** [spb-frontend/spb-frontend.ru#67]

**Comment by lapanoid** [comment]
https://github.com/spb-frontend/spb-frontend.ru/pull/69

**Comment by lapanoid** [comment]
@dshved @Akurganow я вмерджил решение @thepocp, тк оно работает https://deploy-preview-78--spb-frontend.netlify.com/podcast/27и лучше с возможностью загрузки, чем вообще без. Но я согласен с @Akurganow что лучше использовать возможности браузера и делать загрузку нативно.

**Comment by dshved** [comment]
@lapanoid текущие ссылки на mp3 файлы браузер не запускает скачивание файла, а начинает воспроизводить. Поэтому нативно и не получалось и пришлось городить такое решение.
