### ISSUE TITLE
Кнопка «назад» не имеет ссылки 

### ISSUE THREAD

**Issue by prosv** [spb-frontend/spb-frontend.ru#79]
href="#"
Не работает без js

**Comment by Akurganow** [comment]
@prosv А какую ссылку туда поставить?
Например на страницу Ситника можно попасть из эпизода подкаста, со страницы /persons и со страницы митапа, т.е на этапе сборки не подставить
Динамически на клиенте, без js тоже работать не будет
Ставить фикс, а потом если есть js переопределять, как-то костыльно

Для начала стоит посчитать сколько у нас было пользователей без js и стоит ли оно того, поисковые роботы `history.goBack()` смогут

**Comment by fogrew** [comment]
А ещё ссылку на профиль [можно открыть из социалки](https://vk.com/wall39550973_6771). И тогда «< назад» никуда и не должно вести.
Имхо, ссылку нужно по дефолту убрать, но динамически добавлять, если `document.referrer` - ваш сайт.

**Comment by lapanoid** [comment]
Кароче убрал кнопку, всем спасибо)
